---
driver:
  name: vagrant
  customize:
    memory: 2048

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04

suites:
  - name: package
    run_list:
      - recipe[elixir::package]
  - name: source
    run_list:
      - recipe[elixir::source]
