---
driver:
  name: vagrant
  customize:
    memory: 2048

provisioner:
  name: chef_zero

platforms:
platforms:
  # - name: ubuntu-16.04
  - name: centos-7.2

suites:
  - name: package
    run_list:
      - recipe[elixir::default]
    attributes:
      elixir:
        install_method: "package"
  - name: source
    run_list:
      - recipe[elixir::default]
    attributes:
      elixir:
        install_method: "source"
